# Generated by Django 4.0.3 on 2022-03-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_mgr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='managers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='managers',
            name='last_name',
        ),
    ]
