# Generated by Django 4.0.3 on 2022-03-21 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_password_remove_managers_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.managers'),
        ),
    ]
