# Generated by Django 4.0.3 on 2022-04-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='employee/images'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
