# Generated by Django 4.0.3 on 2022-04-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employee_pic_alter_managers_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managers',
            name='pic',
        ),
    ]
