# Generated by Django 4.0.3 on 2022-04-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_remove_managers_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='media'),
        ),
    ]
